export const currency = [
  { label: "AFN - Afghan Afghani (؋)", value: "afn" },
  { label: "ALL - Albanian Lek (Lek)", value: "all" },
  { label: "AMD - Armenian Dram (֏)", value: "amd" },
  { label: "AOA - Angolan Kwanza (Kz)", value: "aoa" },
  { label: "ARS - Argentine Peso ($)", value: "ars" },
  { label: "AUD - Australian Dollar (A$)", value: "aud" },
  { label: "AWG - Aruban Florin (ƒ)", value: "awg" },
  { label: "AZN - Azerbaijani Manat (₼)", value: "azn" },
  { label: "BBD - Barbadian Dollar (Bds$)", value: "bbd" },
  { label: "BDT - Bangladeshi Taka (৳)", value: "bdt" },
  { label: "BGN - Bulgarian Lev (лв)", value: "bgn" },
  { label: "BHD - Bahraini Dinar (د.ب)", value: "bhd" },
  { label: "BIF - Burundian Franc (FBu)", value: "bif" },
  { label: "BMD - Bermudian Dollar (BD$)", value: "bmd" },
  { label: "BND - Brunei Dollar (B$)", value: "bnd" },
  { label: "BOB - Bolivian Boliviano (Bs.)", value: "bob" },
  { label: "BRL - Brazilian Real (R$)", value: "brl" },
  { label: "BSD - Bahamian Dollar (BSD$)", value: "bsd" },
  { label: "BTN - Bhutanese Ngultrum (Nu.)", value: "btn" },
  { label: "BWP - Botswanan Pula (P)", value: "bwp" },
  { label: "BYN - Belarusian Ruble (Br)", value: "byn" },
  { label: "BZD - Belize Dollar (BZ$)", value: "bzd" },
  { label: "CAD - Canadian Dollar (C$)", value: "cad" },
  { label: "CHF - Swiss Franc (CHF)", value: "chf" },
  { label: "CLP - Chilean Peso ($)", value: "clp" },
  { label: "CNY - Chinese Yuan Renminbi (¥)", value: "cny" },
  { label: "COP - Colombian Peso ($)", value: "cop" },
  { label: "CRC - Costa Rican Colón (₡)", value: "crc" },
  { label: "CUP - Cuban Peso (₱)", value: "cup" },
  { label: "CVE - Cape Verdean Escudo (CVE)", value: "cve" },
  { label: "CZK - Czech Koruna (Kč)", value: "czk" },
  { label: "DJF - Djiboutian Franc (Fdj)", value: "djf" },
  { label: "DKK - Danish Krone (kr)", value: "dkk" },
  { label: "DOP - Dominican Peso (RD$)", value: "dop" },
  { label: "DZD - Algerian Dinar (د.ج)", value: "dzd" },
  { label: "EGP - Egyptian Pound (ج.م)", value: "egp" },
  { label: "ERN - Eritrean Nakfa (ERN)", value: "ern" },
  { label: "ETB - Ethiopian Birr (ETB)", value: "etb" },
  { label: "EUR - Euro (€)", value: "eur" },
  { label: "FJD - Fijian Dollar (FJ$)", value: "fjd" },
  { label: "FKP - Falkland Islands Pound (FKP)", value: "fkp" },
  { label: "GBP - British Pound Sterling (£)", value: "gbp" },
  { label: "GEL - Georgian Lari (ლ)", value: "gel" },
  { label: "GIP - Gibraltar Pound (GIP)", value: "gip" },
  { label: "GMD - Gambian Dalasi (GMD)", value: "gmd" },
  { label: "GNF - Guinean Franc (FG)", value: "gnf" },
  { label: "GTQ - Guatemalan Quetzal (Q)", value: "gtq" },
  { label: "GYD - Guyanaese Dollar (GY$)", value: "gyd" },
  { label: "HKD - Hong Kong Dollar (HK$)", value: "hkd" },
  { label: "HNL - Honduran Lempira (L)", value: "hnl" },
  { label: "HRK - Croatian Kuna (kn)", value: "hrk" },
  { label: "HTG - Haitian Gourde (HTG)", value: "htg" },
  { label: "HUF - Hungarian Forint (Ft)", value: "huf" },
  { label: "IDR - Indonesian Rupiah (Rp)", value: "idr" },
  { label: "ILS - Israeli New Sheqel (₪)", value: "ils" },
  { label: "INR - Indian Rupee (₹)", value: "inr" },
  { label: "IQD - Iraqi Dinar (ع.د)", value: "iqd" },
  { label: "IRR - Iranian Rial (﷼)", value: "irr" },
  { label: "ISK - Icelandic Króna (kr)", value: "isk" },
  { label: "JMD - Jamaican Dollar (J$)", value: "jmd" },
  { label: "JPY - Japanese Yen (¥)", value: "jpy" },
  { label: "KES - Kenyan Shilling (KSh)", value: "kes" },
  { label: "KHR - Cambodian Riel (៛)", value: "khr" },
  { label: "KMF - Comorian Franc (CF)", value: "kmf" },
  { label: "KRW - South Korean Won (₩)", value: "krw" },
  { label: "KWD - Kuwaiti Dinar (د.ك)", value: "kwd" },
  { label: "KYD - Cayman Islands Dollar (CI$)", value: "kyd" },
  { label: "KZT - Kazakhstani Tenge (₸)", value: "kzt" },
  { label: "LAK - Laotian Kip (₭)", value: "lak" },
  { label: "LBP - Lebanese Pound (ل.ل)", value: "lbp" },
  { label: "LKR - Sri Lankan Rupee (₨)", value: "lkr" },
  { label: "LRD - Liberian Dollar (LR$)", value: "lrd" },
  { label: "LSL - Lesotho Loti (L)", value: "lsl" },
  { label: "LYD - Libyan Dinar (ل.د)", value: "lyd" },
  { label: "MAD - Moroccan Dirham (د.م.)", value: "mad" },
  { label: "MDL - Moldovan Leu (MDL)", value: "mdl" },
  { label: "MGA - Malagasy Ariary (Ar)", value: "mga" },
  { label: "MKD - Macedonian Denar (ден)", value: "mkd" },
  { label: "MMK - Myanma Kyat (K)", value: "mmk" },
  { label: "MNT - Mongolian Tugrik (₮)", value: "mnt" },
  { label: "MOP - Macanese Pataca (MOP$)", value: "mop" },
  { label: "MUR - Mauritian Rupee (₨)", value: "mur" },
  { label: "MVR - Maldivian Rufiyaa (Rf)", value: "mvr" },
  { label: "MWK - Malawian Kwacha (MK)", value: "mwk" },
  { label: "MXN - Mexican Peso (Mex$)", value: "mxn" },
  { label: "MYR - Malaysian Ringgit (RM)", value: "myr" },
  { label: "MZN - Mozambican Metical (MT)", value: "mzn" },
  { label: "NAD - Namibian Dollar (N$)", value: "nad" },
  { label: "NGN - Nigerian Naira (₦)", value: "ngn" },
  { label: "NIO - Nicaraguan Córdoba (C$)", value: "nio" },
  { label: "NOK - Norwegian Krone (kr)", value: "nok" },
  { label: "NPR - Nepalese Rupee (₨)", value: "npr" },
  { label: "NZD - New Zealand Dollar (NZ$)", value: "nzd" },
  { label: "OMR - Omani Rial (ر.ع.)", value: "omr" },
  { label: "PAB - Panamanian Balboa (B/.)", value: "pab" },
  { label: "PEN - Peruvian Nuevo Sol (S/.)", value: "pen" },
  { label: "PGK - Papua New Guinean Kina (K)", value: "pgk" },
  { label: "PHP - Philippine Peso (₱)", value: "php" },
  { label: "PKR - Pakistani Rupee (₨)", value: "pkr" },
  { label: "PLN - Polish Złoty (zł)", value: "pln" },
  { label: "PYG - Paraguayan Guarani (₲)", value: "pyg" },
  { label: "QAR - Qatari Riyal (ر.ق)", value: "qar" },
  { label: "RON - Romanian Leu (lei)", value: "ron" },
  { label: "RSD - Serbian Dinar (дин)", value: "rsd" },
  { label: "RUB - Russian Ruble (₽)", value: "rub" },
  { label: "RWF - Rwandan Franc (FR)", value: "rwf" },
  { label: "SAR - Saudi Riyal (ر.س)", value: "sar" },
  { label: "SBD - Solomon Islands Dollar (SI$)", value: "sbd" },
  { label: "SCR - Seychellois Rupee (₨)", value: "scr" },
  { label: "SEK - Swedish Krona (kr)", value: "sek" },
  { label: "SGD - Singapore Dollar (S$)", value: "sgd" },
  { label: "SHP - Saint Helena Pound (SHP)", value: "shp" },
  { label: "SLL - Sierra Leonean Leone (Le)", value: "sll" },
  { label: "SOS - Somali Shilling (Sh.So.)", value: "sos" },
  { label: "SRD - Surinamese Dollar (SRD$)", value: "srd" },
  { label: "SYP - Syrian Pound (ل.س)", value: "syp" },
  { label: "SZL - Eswatini Lilangeni (L)", value: "szl" },
  { label: "THB - Thai Baht (฿)", value: "thb" },
  { label: "TJS - Tajikistani Somoni (TJS)", value: "tjs" },
  { label: "TMT - Turkmenistan Manat (TMT)", value: "tmt" },
  { label: "TND - Tunisian Dinar (د.ت)", value: "tnd" },
  { label: "TOP - Tongan Pa'anga (T$)", value: "top" },
  { label: "TRY - Turkish Lira (₺)", value: "try" },
  { label: "TWD - New Taiwan Dollar (NT$)", value: "twd" },
  { label: "TZS - Tanzanian Shilling (TSh)", value: "tzs" },
  { label: "UAH - Ukrainian Hryvnia (₴)", value: "uah" },
  { label: "UGX - Ugandan Shilling (USh)", value: "ugx" },
  { label: "USD - United States Dollar ($)", value: "usd" },
  { label: "UYU - Uruguayan Peso (UYU$)", value: "uyu" },
  { label: "UZS - Uzbekistan Som (UZS)", value: "uzs" },
  { label: "VND - Vietnamese Dong (₫)", value: "vnd" },
  { label: "VUV - Vanuatu Vatu (VT)", value: "vuv" },
  { label: "WST - Samoan Tala (WS$)", value: "wst" },
  { label: "XCD - East Caribbean Dollar (EC$)", value: "xcd" },
  { label: "XOF - West African CFA Franc (CFA)", value: "xof" },
  { label: "XPF - CFP Franc (CFPF)", value: "xpf" },
  { label: "YER - Yemeni Rial (﷼)", value: "yer" },
  { label: "ZAR - South African Rand (R)", value: "zar" },
  { label: "ZMW - Zambian Kwacha (ZK)", value: "zmw" },
];
